model_type: cyclegan
domain_X: horse
domain_Y: zebra
test_X: horse_test
test_Y: zebra_test
max_epoch: 200
batch_size: 2
image_size: 256
learning_rate: 0.0002
lambda_cyc: 10
gen_num_channels: 64
dis_num_channels: 64
use_idt: False