model_type: cyclegan
domain_X: cheese_cake
domain_Y: chocolate_cake
test_X: cheese_cake_test
test_Y: chocolate_cake_test
max_epoch: 200
batch_size: 2
image_size: 256
learning_rate: 0.0002
lambda_cyc: 10
gen_num_channels: 64
dis_num_channels: 64
use_idt: False