model_type: munit
domain_X: horse
domain_Y: zebra
test_X: horse_test
test_Y: zebra_test
max_epoch: 500
batch_size: 1
image_size: 256
learning_rate: 0.0002
lambda_image: 10
lambda_content: 1
lambda_style: 1
num_channels: 64
style_dim: 8
use_idt: False